### PR TITLE
29 rename files to be more pascal -follow up

### PR DESCRIPTION
**Pull request by mvancanneyt**
I had some committed but not pushed changes in my previous PR :-(

I renamed Settings again: IMO Settings is a too common or generic name for a unit. 
I have such a unit in many old projects.

In my opinion all files in the LSPProtocol package should at least start with LSP, 

If you wish to differentiate files that are part of the protocol from files that are not part of the protocol,
I think we can add another prefix (such as I did with Bridge). 

If LSP.Settings is not ok for you, let me know what you prefer:
for me LSP.Bridge.Settings or LSP.Server.Settings is also fine.

### CODE REVIEW

**Comment by genericptr** [comment]
Sorry if I made you lose some work. My problem with those names is that those files are not part of the LSP. Symbols, Settings and Commands are just part of this language server and some other utility files are just functions and even less related. I guess I see your idea of naming them "bridge"  but it feels wrong to have them part of the LSP files. However the other do include server implementations so it's not purely segregated by any means.

It sounds like we're getting setup for all files being prefixed LSP now which is kind of redundant.

**Comment by mvancanneyt** [comment]
If you prefer, I can rename the 'Bridge' and 'Settings' to use LSPServer as a prefix ?
Everything is better than no prefix in the package units...
So LSPServer.Settings, LSPServer.CodeUtils,. LSPServer.Symbols etc.

**Comment by genericptr** [comment]
Is the idea here that we want to prefix all files that are not directly part of the LSP with this prefix? If so maybe something shorter like Pasls. even just Server? Sorry I'm being picky but this is the first time I've used this pattern so it's all kind of strange to me. I do like the LSP prefix though because it helps identify the files correctly as being part of the protocol itself.

**Comment by mvancanneyt** [comment]
The idea is indeed to prefix all units. 

Firstly, simply for consistency: it's not logical to have a package with some units prefixed and some not.

Secondly, some names like 'Settings' and 'LazConfig' are simply too generic. 
I had a quick count, I have at least 10 units named 'settings' in the various projects I have on my disk.
This is OK in a final project, but not in a package which is intended to be used in other projects.

I agree with your remark that LSP should be used to identify files as part of the protocol. 
Since the other units (not part of the protocol) are meant to be part of a LSP server, the 
use of LSPServer or LSPBridge seems appropriate.

**Comment by genericptr** [comment]
Agreed those are generic names which need a prefix. So if this is going on all files can we just do something short like: Pasls.Settings, Server.Settings, Support.Settings, Extra.Settings for the Settings.pas file. Is that ok? LSP was a nice prefix for those file because they're literally modeled after the protocol, i.e. you could look at the spec and correlate to those files, however for the rest they have nothing to do with LSP itself but rather just support or utility units.

**Comment by mvancanneyt** [comment]
Perfect. I will change the names accordingly, and push to this branch, the merge should then have the updated files..

**Comment by mvancanneyt** [comment]
I pushed the change. Please let me know if I missed something. 

I'm not entirely sure about LSP.Symbols, for the moment I left it in the LSP namespace. 

(since the symbols are the basis of everything)

I also checked the uses clause of the main program, and added what was missing.

**Comment by genericptr** [comment]
LSP.Symbols should be PasLS since it's more about code tools and my symbol database.

**Comment by mvancanneyt** [comment]
OK. Will change accordingly

**Comment by mvancanneyt** [comment]
Renamed LSP.Symbols to PasLS.Symbols

**Comment by mvancanneyt** [comment]
Thanks !

**Pull request merged**
